package com.eightbyte.mapper;

import com.eightbyte.domain.ExpressCarrierRelation;
import com.eightbyte.domain.ExpressCarrierRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpressCarrierRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    long countByExample(ExpressCarrierRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int deleteByExample(ExpressCarrierRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int insert(ExpressCarrierRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int insertSelective(ExpressCarrierRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    List<ExpressCarrierRelation> selectByExample(ExpressCarrierRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    ExpressCarrierRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExpressCarrierRelation record, @Param("example") ExpressCarrierRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExpressCarrierRelation record, @Param("example") ExpressCarrierRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExpressCarrierRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpressCarrierRelation record);
}