package com.eightbyte.mapper;

import com.eightbyte.domain.ExpressTraceRecord;
import com.eightbyte.domain.ExpressTraceRecordExample;

import java.util.List;

import com.eightbyte.vo.TraceRecordCountVo;
import org.apache.ibatis.annotations.Param;

public interface ExpressTraceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    long countByExample(ExpressTraceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int deleteByExample(ExpressTraceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int insert(ExpressTraceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int insertSelective(ExpressTraceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    List<ExpressTraceRecord> selectByExample(ExpressTraceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    ExpressTraceRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExpressTraceRecord record, @Param("example") ExpressTraceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExpressTraceRecord record, @Param("example") ExpressTraceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExpressTraceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpressTraceRecord record);

    List<TraceRecordCountVo> selectEveryExpressRecordCount();

    ExpressTraceRecord selectMaxTraceRecord(int expressId);
}