package com.eightbyte.mapper;

import com.eightbyte.domain.RegisterKey;
import com.eightbyte.domain.RegisterKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    long countByExample(RegisterKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int deleteByExample(RegisterKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int insert(RegisterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int insertSelective(RegisterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    List<RegisterKey> selectByExample(RegisterKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    RegisterKey selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RegisterKey record, @Param("example") RegisterKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RegisterKey record, @Param("example") RegisterKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RegisterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_register_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegisterKey record);
}