package com.eightbyte.domain;

import lombok.Builder;

import java.util.Date;

@Builder
public class ClientInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.cert_num
     *
     * @mbg.generated
     */
    private String certNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.detailed_addr
     *
     * @mbg.generated
     */
    private String detailedAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_client_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_info
     *
     * @mbg.generated
     */
    public ClientInfo(Integer id, String name, String phone, String certNum, String province, String city, String district, String detailedAddr, Date createTime, Date updateTime) {
        this.id = id;
        this.name = name;
        this.phone = phone;
        this.certNum = certNum;
        this.province = province;
        this.city = city;
        this.district = district;
        this.detailedAddr = detailedAddr;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_client_info
     *
     * @mbg.generated
     */
    public ClientInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.id
     *
     * @return the value of t_client_info.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.id
     *
     * @param id the value for t_client_info.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.name
     *
     * @return the value of t_client_info.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.name
     *
     * @param name the value for t_client_info.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.phone
     *
     * @return the value of t_client_info.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.phone
     *
     * @param phone the value for t_client_info.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.cert_num
     *
     * @return the value of t_client_info.cert_num
     * @mbg.generated
     */
    public String getCertNum() {
        return certNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.cert_num
     *
     * @param certNum the value for t_client_info.cert_num
     * @mbg.generated
     */
    public void setCertNum(String certNum) {
        this.certNum = certNum == null ? null : certNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.province
     *
     * @return the value of t_client_info.province
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.province
     *
     * @param province the value for t_client_info.province
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.city
     *
     * @return the value of t_client_info.city
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.city
     *
     * @param city the value for t_client_info.city
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.district
     *
     * @return the value of t_client_info.district
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.district
     *
     * @param district the value for t_client_info.district
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.detailed_addr
     *
     * @return the value of t_client_info.detailed_addr
     * @mbg.generated
     */
    public String getDetailedAddr() {
        return detailedAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.detailed_addr
     *
     * @param detailedAddr the value for t_client_info.detailed_addr
     * @mbg.generated
     */
    public void setDetailedAddr(String detailedAddr) {
        this.detailedAddr = detailedAddr == null ? null : detailedAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.create_time
     *
     * @return the value of t_client_info.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.create_time
     *
     * @param createTime the value for t_client_info.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_client_info.update_time
     *
     * @return the value of t_client_info.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_client_info.update_time
     *
     * @param updateTime the value for t_client_info.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}