package com.eightbyte.domain;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.Date;

@Builder
@Setter
@Getter
@ToString
public class ExpressCarrierRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.express_id
     *
     * @mbg.generated
     */
    private Integer expressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.source
     *
     * @mbg.generated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_carrier_relation.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    public ExpressCarrierRelation(Integer id, Integer expressId, Integer userId, Integer source, Date createTime, Date updateTime) {
        this.id = id;
        this.expressId = expressId;
        this.userId = userId;
        this.source = source;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_carrier_relation
     *
     * @mbg.generated
     */
    public ExpressCarrierRelation() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.id
     *
     * @return the value of t_express_carrier_relation.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.id
     *
     * @param id the value for t_express_carrier_relation.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.express_id
     *
     * @return the value of t_express_carrier_relation.express_id
     * @mbg.generated
     */
    public Integer getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.express_id
     *
     * @param expressId the value for t_express_carrier_relation.express_id
     * @mbg.generated
     */
    public void setExpressId(Integer expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.user_id
     *
     * @return the value of t_express_carrier_relation.user_id
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.user_id
     *
     * @param userId the value for t_express_carrier_relation.user_id
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.source
     *
     * @return the value of t_express_carrier_relation.source
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.source
     *
     * @param source the value for t_express_carrier_relation.source
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.create_time
     *
     * @return the value of t_express_carrier_relation.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.create_time
     *
     * @param createTime the value for t_express_carrier_relation.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_carrier_relation.update_time
     *
     * @return the value of t_express_carrier_relation.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_carrier_relation.update_time
     *
     * @param updateTime the value for t_express_carrier_relation.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}