package com.eightbyte.domain;

import java.util.Date;

public class ExpressTraceRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.express_id
     *
     * @mbg.generated
     */
    private Integer expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.express_order_no
     *
     * @mbg.generated
     */
    private String expressOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.from_addr
     *
     * @mbg.generated
     */
    private String fromAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.to_addr
     *
     * @mbg.generated
     */
    private String toAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.is_to
     *
     * @mbg.generated
     */
    private Integer isTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.express_status
     *
     * @mbg.generated
     */
    private Integer expressStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_express_trace_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    public ExpressTraceRecord(Integer id, Integer expressId, String expressOrderNo, String fromAddr, String toAddr, Integer isTo, Integer expressStatus, Date createTime, Date updateTime) {
        this.id = id;
        this.expressId = expressId;
        this.expressOrderNo = expressOrderNo;
        this.fromAddr = fromAddr;
        this.toAddr = toAddr;
        this.isTo = isTo;
        this.expressStatus = expressStatus;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_express_trace_record
     *
     * @mbg.generated
     */
    public ExpressTraceRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.id
     *
     * @return the value of t_express_trace_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.id
     *
     * @param id the value for t_express_trace_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.express_id
     *
     * @return the value of t_express_trace_record.express_id
     *
     * @mbg.generated
     */
    public Integer getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.express_id
     *
     * @param expressId the value for t_express_trace_record.express_id
     *
     * @mbg.generated
     */
    public void setExpressId(Integer expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.express_order_no
     *
     * @return the value of t_express_trace_record.express_order_no
     *
     * @mbg.generated
     */
    public String getExpressOrderNo() {
        return expressOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.express_order_no
     *
     * @param expressOrderNo the value for t_express_trace_record.express_order_no
     *
     * @mbg.generated
     */
    public void setExpressOrderNo(String expressOrderNo) {
        this.expressOrderNo = expressOrderNo == null ? null : expressOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.from_addr
     *
     * @return the value of t_express_trace_record.from_addr
     *
     * @mbg.generated
     */
    public String getFromAddr() {
        return fromAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.from_addr
     *
     * @param fromAddr the value for t_express_trace_record.from_addr
     *
     * @mbg.generated
     */
    public void setFromAddr(String fromAddr) {
        this.fromAddr = fromAddr == null ? null : fromAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.to_addr
     *
     * @return the value of t_express_trace_record.to_addr
     *
     * @mbg.generated
     */
    public String getToAddr() {
        return toAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.to_addr
     *
     * @param toAddr the value for t_express_trace_record.to_addr
     *
     * @mbg.generated
     */
    public void setToAddr(String toAddr) {
        this.toAddr = toAddr == null ? null : toAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.is_to
     *
     * @return the value of t_express_trace_record.is_to
     *
     * @mbg.generated
     */
    public Integer getIsTo() {
        return isTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.is_to
     *
     * @param isTo the value for t_express_trace_record.is_to
     *
     * @mbg.generated
     */
    public void setIsTo(Integer isTo) {
        this.isTo = isTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.express_status
     *
     * @return the value of t_express_trace_record.express_status
     *
     * @mbg.generated
     */
    public Integer getExpressStatus() {
        return expressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.express_status
     *
     * @param expressStatus the value for t_express_trace_record.express_status
     *
     * @mbg.generated
     */
    public void setExpressStatus(Integer expressStatus) {
        this.expressStatus = expressStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.create_time
     *
     * @return the value of t_express_trace_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.create_time
     *
     * @param createTime the value for t_express_trace_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_express_trace_record.update_time
     *
     * @return the value of t_express_trace_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_express_trace_record.update_time
     *
     * @param updateTime the value for t_express_trace_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}